/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smpaint_3;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.media.Time;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * Reproductor de sonidos
 * @author Nikolai
 */
public class AudioPlayer extends MPlayer {
    //Variables
    Timer timer;
    double dubTime;
    
    //Constructor
    /**
     * Inicializa el reproductor y empieza la reproducción
     * @param padre MainWindow
     * @param f Fichero de video
     */
    public AudioPlayer(javax.swing.JFrame padre, File f) { super(padre, f, true);
        initComponents();
        int delay = 1000;

        timer = new Timer(delay, taskPerformer);
        timer.start();
        
        dubTime = 0;
        Date date = new Date((long)(dubTime*1000));
        String formattedTime = new SimpleDateFormat("mm:ss").format(date);        
        timeLabel.setText(formattedTime);
        
        durationSlider.setMaximum((int)p.getDuration().getSeconds());
    } 
    
    //Manejador de eventos del timer
    ActionListener taskPerformer = new ActionListener() {
            @Override
        public void actionPerformed(ActionEvent evt){
            dubTime = p.getMediaTime().getSeconds();
            durationSlider.setValue((int)dubTime);
           
            Date date = new Date((long)(dubTime*1000));
            String formattedTime = new SimpleDateFormat("mm:ss").format(date);        
            timeLabel.setText(formattedTime);        
            repaint();
        }
    };
    
    //Métodos
    /**
     * Mata elegantemente al reproductor
     */
    public void Kill() {
        try{
            p.stop();
            p.close();
            timer.stop();
        } catch(Exception e) {JOptionPane.showMessageDialog(null, e.toString());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  

    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        durationSlider = new javax.swing.JSlider();
        pauseButton = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smpaint_3/play.png"))); // NOI18N
        playButton.setBorderPainted(false);
        playButton.setFocusPainted(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        durationSlider.setValue(0);
        durationSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                durationSliderMouseReleased(evt);
            }
        });

        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smpaint_3/pause.png"))); // NOI18N
        pauseButton.setBorderPainted(false);
        pauseButton.setFocusPainted(false);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(durationSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(durationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        try{
            p.start();
        } catch(Exception e) {JOptionPane.showMessageDialog(null, e.toString());}
    }//GEN-LAST:event_playButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        try{
            p.stop();
        } catch(Exception e) {JOptionPane.showMessageDialog(null, e.toString());}
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void durationSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_durationSliderMouseReleased
        // TODO add your handling code here:
        try{
            p.setMediaTime(new Time((double)durationSlider.getValue()));
        } catch(Exception e) {JOptionPane.showMessageDialog(null, e.toString());}
    }//GEN-LAST:event_durationSliderMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider durationSlider;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
