/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smpaint_3;

import java.io.File;
import javax.swing.JOptionPane;

/**
 * Reproductor de vídeos
 * @author Nikolai
 */
public class VideoPlayer extends MPlayer {
    //Construcotres
    /**
     * Inicializa el reproductor y empieza la reproducción
     * @param padre MainWindow
     * @param f Fichero de video
     */
    public VideoPlayer(javax.swing.JFrame padre, File f) {super(padre, f, false);
        initComponents();
        
        try{
            p.start();
            p.addControllerListener(new MyMediaManager(this, videoWindow));
        } catch(Exception e) {JOptionPane.showMessageDialog(null, e.toString());}
    }
    
    /**
     * Mata elegantemente al reproductor
     */
    public void Kill() {
        try{
            p.stop();
            p.close();
        } catch(Exception e) {JOptionPane.showMessageDialog(null, e.toString());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoWindow = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        videoWindow.setLayout(new java.awt.BorderLayout());
        add(videoWindow, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel videoWindow;
    // End of variables declaration//GEN-END:variables
}
